[2023-11-16T20:49:24.775+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: two_task_dag.bash_task_0 manual__2023-11-16T20:49:21.787537+00:00 [queued]>
[2023-11-16T20:49:24.780+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: two_task_dag.bash_task_0 manual__2023-11-16T20:49:21.787537+00:00 [queued]>
[2023-11-16T20:49:24.780+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-16T20:49:24.781+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-16T20:49:24.781+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-16T20:49:24.824+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): bash_task_0> on 2023-11-16 20:49:21.787537+00:00
[2023-11-16T20:49:24.827+0000] {standard_task_runner.py:55} INFO - Started process 30135 to run task
[2023-11-16T20:49:24.830+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'two_task_dag', 'bash_task_0', 'manual__2023-11-16T20:49:21.787537+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/two_task_dag.py', '--cfg-path', '/tmp/tmpz93jc7jq']
[2023-11-16T20:49:24.831+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask bash_task_0
[2023-11-16T20:49:24.897+0000] {task_command.py:388} INFO - Running <TaskInstance: two_task_dag.bash_task_0 manual__2023-11-16T20:49:21.787537+00:00 [running]> on host codespaces-65b6ca
[2023-11-16T20:49:24.998+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Raul
AIRFLOW_CTX_DAG_ID=two_task_dag
AIRFLOW_CTX_TASK_ID=bash_task_0
AIRFLOW_CTX_EXECUTION_DATE=2023-11-16T20:49:21.787537+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-16T20:49:21.787537+00:00
[2023-11-16T20:49:25.000+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-16T20:49:25.000+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '"First Airflow Task!"']
[2023-11-16T20:49:25.008+0000] {subprocess.py:86} INFO - Output:
[2023-11-16T20:49:25.010+0000] {subprocess.py:93} INFO - /usr/bin/bash: First Airflow Task!: command not found
[2023-11-16T20:49:25.010+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-16T20:49:25.015+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-16T20:49:25.016+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=two_task_dag, task_id=bash_task_0, execution_date=20231116T204921, start_date=20231116T204924, end_date=20231116T204925
[2023-11-16T20:49:25.071+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task bash_task_0 (Bash command failed. The command returned a non-zero exit code 127.; 30135)
[2023-11-16T20:49:25.083+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-16T20:49:25.095+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
