[2023-11-16T20:49:49.431+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: two_task_dag.bash_task_0 manual__2023-11-16T20:49:46.300550+00:00 [queued]>
[2023-11-16T20:49:49.437+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: two_task_dag.bash_task_0 manual__2023-11-16T20:49:46.300550+00:00 [queued]>
[2023-11-16T20:49:49.437+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-16T20:49:49.437+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-16T20:49:49.437+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-16T20:49:49.478+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): bash_task_0> on 2023-11-16 20:49:46.300550+00:00
[2023-11-16T20:49:49.481+0000] {standard_task_runner.py:55} INFO - Started process 30302 to run task
[2023-11-16T20:49:49.485+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'two_task_dag', 'bash_task_0', 'manual__2023-11-16T20:49:46.300550+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/two_task_dag.py', '--cfg-path', '/tmp/tmpyxz4ej8u']
[2023-11-16T20:49:49.486+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask bash_task_0
[2023-11-16T20:49:49.546+0000] {task_command.py:388} INFO - Running <TaskInstance: two_task_dag.bash_task_0 manual__2023-11-16T20:49:46.300550+00:00 [running]> on host codespaces-65b6ca
[2023-11-16T20:49:49.636+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Raul
AIRFLOW_CTX_DAG_ID=two_task_dag
AIRFLOW_CTX_TASK_ID=bash_task_0
AIRFLOW_CTX_EXECUTION_DATE=2023-11-16T20:49:46.300550+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-16T20:49:46.300550+00:00
[2023-11-16T20:49:49.637+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-16T20:49:49.638+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '"First Airflow Task!"']
[2023-11-16T20:49:49.645+0000] {subprocess.py:86} INFO - Output:
[2023-11-16T20:49:49.647+0000] {subprocess.py:93} INFO - /usr/bin/bash: First Airflow Task!: command not found
[2023-11-16T20:49:49.648+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-16T20:49:49.653+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-16T20:49:49.656+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=two_task_dag, task_id=bash_task_0, execution_date=20231116T204946, start_date=20231116T204949, end_date=20231116T204949
[2023-11-16T20:49:49.701+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 4 for task bash_task_0 (Bash command failed. The command returned a non-zero exit code 127.; 30302)
[2023-11-16T20:49:49.736+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-16T20:49:49.750+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
